apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "chart.fullname" . }}-extension-apiserver-authentication-reader
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "chart.fullname" . }}-extension-apiserver-authentication-reader'
subjects:
- kind: ServiceAccount
  name: '{{ include "chart.fullname" . }}-keptn-scheduler'
  namespace: '{{ .Release.Namespace }}'