apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chart.fullname" . }}-hpa-controller-keptn-metrics
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "chart.fullname" . }}-server-resources'
subjects:
- kind: ServiceAccount
  name: horizontal-pod-autoscaler
  namespace: '{{ .Release.Namespace }}'