apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-klc-webhook-service
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.klcWebhookService.type }}
  selector:
    control-plane: controller-manager
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.klcWebhookService.ports | toYaml | nindent 2 -}}