apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-klt-proxy-role
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: cert-manager
    app.kubernetes.io/part-of: cert-manager
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chart.fullname" . }}-klt-proxy-rolebinding
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: klt-cert-manager
    app.kubernetes.io/part-of: klt-cert-manager
  {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "chart.fullname" . }}-klt-proxy-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "chart.fullname" . }}-klt-cert-manager'
  namespace: '{{ .Release.Namespace }}'