apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "chart.fullname" . }}-klt-cert-manager-role-binding
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: klt-cert-manager
    app.kubernetes.io/part-of: klt-cert-manager
  {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "chart.fullname" . }}-klt-cert-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "chart.fullname" . }}-klt-cert-manager'
  namespace: '{{ .Release.Namespace }}'