apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "chart.fullname" . }}-metrics-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "chart.fullname" . }}-
  labels:
    keptn.sh/inject-cert: "true"
  {{- include "chart.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "chart.fullname" . }}-metrics-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-metrics-keptn-sh-v1alpha3-keptnmetric
  failurePolicy: Fail
  name: vkeptnmetric.kb.io
  rules:
  - apiGroups:
    - metrics.keptn.sh
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - keptnmetrics
  sideEffects: None