## @section Keptn Scheduler
## @extra scheduler.scheduler.containerSecurityContext Sets security context
## @skip scheduler.scheduler.containerSecurityContext.allowPrivilegeEscalation
## @skip scheduler.scheduler.containerSecurityContext.capabilities.drop
## @skip scheduler.scheduler.containerSecurityContext.privileged
## @skip scheduler.scheduler.containerSecurityContext.readOnlyRootFilesystem
## @skip scheduler.scheduler.containerSecurityContext.runAsNonRoot
## @skip scheduler.scheduler.containerSecurityContext.runAsUser
## @skip scheduler.scheduler.containerSecurityContext.seccompProfile.type

## @param scheduler.scheduler.env.otelCollectorUrl sets url for open telemetry collector

## @param scheduler.scheduler.image.repository set image repository for scheduler
## @param scheduler.scheduler.image.tag set image tag for scheduler
## @param scheduler.scheduler.imagePullPolicy set image pull policy for scheduler

## @extra scheduler.scheduler.livenessProbe customizable liveness probe for the scheduler
## @skip scheduler.scheduler.livenessProbe.httpGet.path
## @skip scheduler.scheduler.livenessProbe.httpGet.port
## @skip scheduler.scheduler.livenessProbe.httpGet.scheme
## @skip scheduler.scheduler.livenessProbe.initialDelaySeconds

## @extra scheduler.scheduler.readinessProbe customizable readiness probe for the scheduler
## @skip scheduler.scheduler.readinessProbe.httpGet.path
## @skip scheduler.scheduler.readinessProbe.httpGet.port
## @skip scheduler.scheduler.readinessProbe.httpGet.scheme

## @extra scheduler.scheduler.resources sets cpu and memory resurces/limits for scheduler
## @skip scheduler.scheduler.resources.limits.cpu
## @skip scheduler.scheduler.resources.limits.memory
## @skip scheduler.scheduler.resources.requests.cpu
## @skip scheduler.scheduler.resources.requests.memory

## @param  schedulerConfig.schedulerConfigYaml.leaderElection.leaderElect enables leader election for multiple replicas of the scheduler
## @param  schedulerConfig.schedulerConfigYaml.profiles[0].plugins.permit.enabled[0].name enables permit plugin
## @param  schedulerConfig.schedulerConfigYaml.profiles[0].schedulerName changes scheduler name

## @param scheduler.nodeSelector adds node selectors for scheduler
## @param scheduler.replicas modifies replicas
## @param scheduler.tolerations adds tolerations for scheduler
## @param scheduler.topologySpreadConstraints add topology constraints for scheduler

## @section Keptn Cert Manager common

## @param     certificateOperator.replicas customize number of replicas

## @param     certificateOperator.nodeSelector specify custom node selectors for cert manager
## @param     certificateOperator.tolerations customize tolerations for cert manager
## @param     certificateOperator.topologySpreadConstraints add topology constraints for cert manager

## @param    lifecycleManagerConfig.controllerManagerConfigYaml.health.healthProbeBindAddress TODO  TODO  TODO
## @param    lifecycleManagerConfig.controllerManagerConfigYaml.leaderElection.leaderElect TODO  TODO  TODO
## @param    lifecycleManagerConfig.controllerManagerConfigYaml.leaderElection.resourceName TODO  TODO  TODO
## @param    lifecycleManagerConfig.controllerManagerConfigYaml.metrics.bindAddress TODO  TODO  TODO
## @param    lifecycleManagerConfig.controllerManagerConfigYaml.webhook.port TODO  TODO  TODO


## @section Keptn Cert Manager controller
## @extra    certificateOperator.manager.containerSecurityContext Sets security context for the cert manager
## @skip     certificateOperator.manager.containerSecurityContext.allowPrivilegeEscalation
## @skip     certificateOperator.manager.containerSecurityContext.capabilities.drop
## @skip     certificateOperator.manager.containerSecurityContext.readOnlyRootFilesystem
## @skip     certificateOperator.manager.containerSecurityContext.runAsGroup
## @skip     certificateOperator.manager.containerSecurityContext.runAsUser
## @skip     certificateOperator.manager.containerSecurityContext.seccompProfile.type

## @param     certificateOperator.manager.image.repository specify repo for manager image
## @param     certificateOperator.manager.image.tag select tag for manager container
## @param     certificateOperator.manager.imagePullPolicy select image pull policy for manager container

## @extra     certificateOperator.manager.livenessProbe custom RBAC proxy liveness probe
## @skip     certificateOperator.manager.livenessProbe.httpGet.path
## @skip     certificateOperator.manager.livenessProbe.httpGet.port
## @skip     certificateOperator.manager.livenessProbe.initialDelaySeconds
## @skip     certificateOperator.manager.livenessProbe.periodSeconds

## @extra    certificateOperator.manager.readinessProbe custom manager readiness probe
## @skip     certificateOperator.manager.readinessProbe.httpGet.path
## @skip     certificateOperator.manager.readinessProbe.httpGet.port
## @skip     certificateOperator.manager.readinessProbe.initialDelaySeconds
## @skip     certificateOperator.manager.readinessProbe.periodSeconds

## @extra    certificateOperator.manager.resources custom limits and requests for manager container
## @skip     certificateOperator.manager.resources.limits.cpu
## @skip     certificateOperator.manager.resources.limits.memory
## @skip     certificateOperator.manager.resources.requests.cpu
## @skip     certificateOperator.manager.resources.requests.memory

## @section Keptn Lifecycle Operator common

## @param   lifecycleOperator.replicas customize number of installed lifecycle operator replicas

## @param    lifecycleWebhookService.ports[0].port TODO  TODO  TODO
## @param    lifecycleWebhookService.ports[0].protocol TODO  TODO  TODO
## @param    lifecycleWebhookService.ports[0].targetPort TODO  TODO  TODO
## @param    lifecycleWebhookService.type TODO  TODO  TODO

## @param   lifecycleOperator.nodeSelector add custom nodes selector to lifecycle operator
## @param   lifecycleOperator.tolerations add custom tolerations to lifecycle operator
## @param   lifecycleOperator.topologySpreadConstraints add custom topology constraints to lifecycle operator

## @section Keptn Lifecycle Operator controller
## @extra   lifecycleOperator.manager.containerSecurityContext Sets security context privileges
## @param   lifecycleOperator.manager.containerSecurityContext.allowPrivilegeEscalation
## @param   lifecycleOperator.manager.containerSecurityContext.capabilities.drop
## @param   lifecycleOperator.manager.containerSecurityContext.privileged
## @param   lifecycleOperator.manager.containerSecurityContext.runAsGroup
## @param   lifecycleOperator.manager.containerSecurityContext.runAsNonRoot
## @param   lifecycleOperator.manager.containerSecurityContext.runAsUser
## @param   lifecycleOperator.manager.containerSecurityContext.seccompProfile.type

## @param   lifecycleOperator.manager.env.keptnAppControllerLogLevel sets the log level of Keptn App Controller
## @param   lifecycleOperator.manager.env.keptnAppVersionControllerLogLevel sets the log level of Keptn AppVersion Controller
## @param   lifecycleOperator.manager.env.keptnEvaluationControllerLogLevel sets the log level of Keptn Evaluation Controller
## @param   lifecycleOperator.manager.env.keptnTaskControllerLogLevel sets the log level of Keptn Task Controller
## @param   lifecycleOperator.manager.env.keptnTaskDefinitionControllerLogLevel sets the log level of Keptn TaskDefinition Controller
## @param   lifecycleOperator.manager.env.keptnWorkloadControllerLogLevel sets the log level of Keptn Workload Controller
## @param   lifecycleOperator.manager.env.keptnWorkloadInstanceControllerLogLevel sets the log level of Keptn WorkloadInstance Controller
## @param   lifecycleOperator.manager.env.optionsControllerLogLevel sets the log level of Keptn Options Controller

## @param   lifecycleOperator.manager.env.otelCollectorUrl Sets the URL for the open telemetry collector
## @param   lifecycleOperator.manager.env.functionRunnerImage specify image for task runtime

## @param   lifecycleOperator.manager.image.repository specify registry for manager image 
## @param   lifecycleOperator.manager.image.tag  select tag for manager image 
## @param   lifecycleOperator.manager.imagePullPolicy specify pull policy for manager image 

## @extra  lifecycleOperator.manager.livenessProbe custom livenessprobe for manager container
## @skip   lifecycleOperator.manager.livenessProbe.httpGet.path
## @skip   lifecycleOperator.manager.livenessProbe.httpGet.port
## @skip   lifecycleOperator.manager.livenessProbe.initialDelaySeconds
## @skip   lifecycleOperator.manager.livenessProbe.periodSeconds

## @extra  lifecycleOperator.manager.readinessProbe custom readinessprobe for manager container
## @skip   lifecycleOperator.manager.readinessProbe.httpGet.path
## @skip   lifecycleOperator.manager.readinessProbe.httpGet.port
## @skip   lifecycleOperator.manager.readinessProbe.initialDelaySeconds
## @skip   lifecycleOperator.manager.readinessProbe.periodSeconds

## @extra  lifecycleOperator.manager.resources specify limits and requests for manager container
## @skip   lifecycleOperator.manager.resources.limits.cpu
## @skip   lifecycleOperator.manager.resources.limits.memory
## @skip   lifecycleOperator.manager.resources.requests.cpu
## @skip   lifecycleOperator.manager.resources.requests.memory


## @section Keptn Metrics Operator common

## @param   metricsOperator.replicas customize number of installed metrics operator replicas

## @param   metricsOperatorService.ports[0].name
## @param   metricsOperatorService.ports[0].port
## @param   metricsOperatorService.ports[0].protocol
## @param   metricsOperatorService.ports[0].targetPort
## @param   metricsOperatorService.ports[1].name
## @param   metricsOperatorService.ports[1].port
## @param   metricsOperatorService.ports[1].targetPort
## @param   metricsOperatorService.ports[2].name
## @param   metricsOperatorService.ports[2].port
## @param   metricsOperatorService.ports[2].protocol
## @param   metricsOperatorService.ports[2].targetPort
## @param   metricsOperatorService.type

## @param      metricsManagerConfig.controllerManagerConfigYaml.health.healthProbeBindAddress TODO  TODO  TODO
## @param      metricsManagerConfig.controllerManagerConfigYaml.leaderElection.leaderElect TODO  TODO  TODO
## @param      metricsManagerConfig.controllerManagerConfigYaml.leaderElection.resourceName TODO  TODO  TODO
## @param      metricsManagerConfig.controllerManagerConfigYaml.metrics.bindAddress TODO  TODO  TODO
## @param      metricsManagerConfig.controllerManagerConfigYaml.webhook.port TODO  TODO  TODO

## @param     metricsWebhookService.ports[0].port TODO  TODO  TODO
## @param     metricsWebhookService.ports[0].protocol TODO  TODO  TODO
## @param     metricsWebhookService.ports[0].targetPort TODO  TODO  TODO
## @param     metricsWebhookService.type TODO  TODO  TODO

## @param    metricsOperator.nodeSelector add custom nodes selector to metrics operator
## @param    metricsOperator.tolerations add custom tolerations to metrics operator
## @param    metricsOperator.topologySpreadConstraints add custom topology constraints to metrics operator

## @section Keptn Metrics Operator controller
## @extra   metricsOperator.manager.containerSecurityContext Sets security context privileges
## @param   metricsOperator.manager.containerSecurityContext.allowPrivilegeEscalation
## @param   metricsOperator.manager.containerSecurityContext.capabilities.drop


## @param   metricsOperator.manager.image.repository specify registry for manager image
## @param   metricsOperator.manager.image.tag  select tag for manager image

## @param   metricsOperator.manager.env.exposeKeptnMetrics enable metrics exporter
## @param   metricsOperator.manager.env.metricsControllerLogLevel sets the log level of Metrics Controller

## @extra  metricsOperator.manager.livenessProbe custom livenessprobe for manager container
## @skip   metricsOperator.manager.livenessProbe.httpGet.path
## @skip   metricsOperator.manager.livenessProbe.httpGet.port
## @skip   metricsOperator.manager.livenessProbe.initialDelaySeconds
## @skip   metricsOperator.manager.livenessProbe.periodSeconds

## @extra  metricsOperator.manager.readinessProbe custom readinessprobe for manager container
## @skip   metricsOperator.manager.readinessProbe.httpGet.path
## @skip   metricsOperator.manager.readinessProbe.httpGet.port
## @skip   metricsOperator.manager.readinessProbe.initialDelaySeconds
## @skip   metricsOperator.manager.readinessProbe.periodSeconds

## @extra  metricsOperator.manager.resources specify limits and requests for manager container
## @skip   metricsOperator.manager.resources.limits.cpu
## @skip   metricsOperator.manager.resources.limits.memory
## @skip   metricsOperator.manager.resources.requests.cpu
## @skip   metricsOperator.manager.resources.requests.memory


## @section Global
## Current available parameters: kubernetesClusterDomain, imagePullSecrets
## @param  kubernetesClusterDomain overrides domain.local
## @param  imagePullSecrets global value for image registry secret
