name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Prepare keys for signing
        env:
          SIGNING_KEY_BASE64: ${{ secrets.HELM_SIGNING_PRIVATE_KEY }}
          SIGNING_KEY_PASSPHRASE_BASE64: ${{ secrets.HELM_SIGNING_PRIVATE_KEY_PASSPHRASE }}
        run: |
          KEY_PATH='.gpg-dir'
          SIGNING_KEY_PATH="$KEY_PATH/secring.gpg"
          SIGNING_KEY_PASSPHRASE_PATH="$KEY_PATH/passphrase"
          mkdir "$KEY_PATH"
          base64 -d <<< "$SIGNING_KEY_BASE64" > "$SIGNING_KEY_PATH"
          base64 -d <<< "$SIGNING_KEY_PASSPHRASE_BASE64" > "$SIGNING_KEY_PASSPHRASE_PATH"
          echo "CR_PASSPHRASE_FILE=$SIGNING_KEY_PATH" >> "$GITHUB_ENV"
          echo "CR_KEYRING="$SIGNING_KEY_PASSPHRASE_PATH" >> "$GITHUB_ENV"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config: cr.yaml
